package com.mentorondemand.paymentservice.controllers;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.mentorondemand.paymentservice.entities.Payments;
import com.mentorondemand.paymentservice.services.PaymentRepository;

@RestController
@CrossOrigin(origins = "http://localhost:4200")
@RequestMapping(path = "/v1/pay")
public class PaymentController {
	@Autowired // This means to get the bean called trainingRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private PaymentRepository paymentRepository;

	@PostMapping(path = "/pay")
	public @ResponseBody Payments pay(@Valid @RequestBody Payments payment) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		return paymentRepository.save(payment);
	}
}
